import React from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "../(public)/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Pegion Trails Digital Agency",
  description: "Generated by create next app",
};

const Layout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex flex-col antialiased justify-between`}
        suppressHydrationWarning
      >
        <div className="flex items-center justify-center h-screen bg-(--color-primary)">
          <div className="w-full md:w-1/2">{children}</div>
          <div className="hidden md:block w-1/2 h-screen">
            <img
              src="/images/auth-bg.png"
              alt=""
              className="w-full h-full object-cover"
            />
          </div>
        </div>
      </body>
    </html>
  );
};

export default Layout;
